export const SILO_PAGES = {
  ia: {
    title: 'Outils IA : comparatifs, alternatives et guides',
    metaTitle: 'Outils IA : comparatif assistants, code, recherche et productivité',
    description: 'Comparez les meilleurs outils IA francophones : ChatGPT, Claude, Gemini, Perplexity, Cursor et alternatives selon vos usages.',
    eyebrow: 'Silo Intelligence artificielle',
    intro: 'Comparateur-Tech aide à choisir les bons outils IA selon le besoin réel : rédaction, recherche, code, productivité, analyse documentaire ou usage étudiant.',
    canonical: '/ia',
    primaryCta: { href: '/comparatifs/meilleurs-outils-ia', label: 'Comparer les outils IA' },
    secondaryCta: { href: '/outils/intelligence-artificielle', label: 'Voir tous les outils IA' },
    sections: [
      { title: 'Assistants IA généralistes', text: 'ChatGPT, Claude et Gemini couvrent les usages quotidiens, mais leurs forces diffèrent selon le contexte, la rédaction, les documents longs ou l’écosystème utilisé.' },
      { title: 'Recherche et productivité', text: 'Perplexity, Notion AI ou DeepL répondent à des besoins plus ciblés : recherche sourcée, organisation, traduction ou synthèse.' },
      { title: 'Développement et API', text: 'Cursor, GitHub Copilot, OpenAI API et Anthropic API doivent être comparés selon le workflow, la confidentialité du code et le coût d’intégration.' },
    ],
    links: [
      { href: '/comparatifs/chatgpt-vs-claude', label: 'ChatGPT vs Claude' },
      { href: '/comparatifs/chatgpt-vs-gemini', label: 'ChatGPT vs Gemini' },
      { href: '/comparatifs/chatgpt-vs-perplexity', label: 'ChatGPT vs Perplexity' },
      { href: '/comparatifs/chatgpt-vs-mistral', label: 'ChatGPT vs Mistral AI' },
      { href: '/guides/meilleure-ia-gratuite', label: 'Meilleure IA gratuite' },
      { href: '/alternatives/alternative-chatgpt', label: 'Alternatives à ChatGPT' },
      { href: '/guides/meilleurs-outils-ia-pour-developpeurs', label: 'IA pour développeurs' },
    ],
    faq: [
      { q: 'Quel outil IA choisir pour commencer ?', a: 'ChatGPT reste le point de départ le plus polyvalent. Claude, Gemini et Perplexity peuvent être plus adaptés selon vos priorités : longs documents, écosystème Google ou recherche web.' },
      { q: 'Faut-il choisir l’outil IA le plus connu ?', a: 'Pas forcément. Le meilleur choix dépend de votre cas d’usage, de votre budget, des limites du plan gratuit et du niveau de confidentialité attendu.' },
      { q: 'Les pages IA contiennent-elles des liens affiliés ?', a: 'Certains liens peuvent être affiliés, sans coût supplémentaire pour vous. La recommandation éditoriale reste basée sur les usages et limites observables.' },
    ],
  },
  vpn: {
    title: 'VPN : comparatifs, alternatives et guides de choix',
    metaTitle: 'VPN : comparatif sécurité, streaming, prix et confidentialité',
    description: 'Comparez les meilleurs VPN : NordVPN, Surfshark, ExpressVPN, Proton VPN et alternatives selon vitesse, sécurité, prix et streaming.',
    eyebrow: 'Silo VPN',
    intro: 'Un VPN doit être choisi selon un besoin concret : protéger une connexion Wi-Fi publique, réduire le pistage, voyager, streamer ou couvrir plusieurs appareils.',
    canonical: '/vpn',
    primaryCta: { href: '/comparatifs/meilleur-vpn', label: 'Comparer les VPN' },
    secondaryCta: { href: '/outils/vpn', label: 'Voir tous les VPN' },
    sections: [
      { title: 'Sécurité et confidentialité', text: 'Nous regardons les protocoles, la politique de logs, le kill switch, la transparence et les fonctions de protection additionnelles.' },
      { title: 'Streaming et voyage', text: 'La vitesse, la stabilité des applications et la couverture pays comptent davantage que les promesses marketing trop générales.' },
      { title: 'Prix et appareils', text: 'Le bon VPN dépend aussi du nombre d’appareils, des promotions, du renouvellement et de la simplicité pour toute la famille.' },
    ],
    links: [
      { href: '/comparatifs/meilleur-vpn', label: 'Meilleur VPN' },
      { href: '/comparatifs/nordvpn-vs-surfshark', label: 'NordVPN vs Surfshark' },
      { href: '/comparatifs/nordvpn-vs-cyberghost', label: 'NordVPN vs CyberGhost' },
      { href: '/comparatifs/expressvpn-vs-surfshark', label: 'ExpressVPN vs Surfshark' },
      { href: '/barometre-prix-vpn', label: 'Baromètre prix VPN 2026' },
      { href: '/guides/meilleur-vpn-android', label: 'VPN Android' },
      { href: '/guides/meilleur-vpn-iphone', label: 'VPN iPhone' },
      { href: '/alternatives/alternative-nordvpn', label: 'Alternatives à NordVPN' },
      { href: '/guides/meilleur-vpn-streaming', label: 'VPN streaming' },
    ],
    faq: [
      { q: 'Quel est le meilleur VPN en 2026 ?', a: 'NordVPN, Surfshark, ExpressVPN, Proton VPN et Mullvad font partie des options à comparer en priorité. Le meilleur choix dépend du budget, du streaming et du niveau de confidentialité recherché.' },
      { q: 'Un VPN rend-il totalement anonyme ?', a: 'Non. Un VPN masque l’adresse IP et chiffre la connexion, mais il ne remplace pas de bonnes pratiques de confidentialité, de navigateur et de gestion des comptes.' },
      { q: 'Les offres VPN changent-elles souvent ?', a: 'Oui. Les prix promotionnels, limites d’appareils et garanties peuvent évoluer. Les pages utilisent donc une formulation prudente quand une donnée doit être vérifiée.' },
    ],
  },
  hebergement: {
    title: 'Hébergement web : choisir une solution fiable',
    metaTitle: 'Hébergement web : comparatif WordPress, prix, support et performance',
    description: 'Comparez Hostinger, o2switch, OVHcloud, Infomaniak, SiteGround et alternatives pour héberger un site web ou WordPress.',
    eyebrow: 'Silo Hébergement',
    intro: 'Le bon hébergement dépend du projet : blog WordPress, site vitrine, e-commerce, besoin français, budget serré ou infrastructure plus avancée.',
    canonical: '/hebergement',
    primaryCta: { href: '/comparatifs/hostinger-vs-o2switch', label: 'Hostinger vs o2switch' },
    secondaryCta: { href: '/outils/hebergement-web', label: 'Voir les hébergeurs' },
    sections: [
      { title: 'WordPress et simplicité', text: 'Installation, sauvegardes, SSL, staging, support et tableau de bord comptent souvent plus que la fiche technique brute.' },
      { title: 'Performance et limites', text: 'Nous comparons les ressources, la vitesse perçue, la capacité d’évolution et les limites qui peuvent gêner un site qui grandit.' },
      { title: 'Support et localisation', text: 'Un support lisible, une offre transparente et la localisation des données peuvent peser lourd pour les projets professionnels.' },
    ],
    links: [
      { href: '/comparatifs/hostinger-vs-o2switch', label: 'Hostinger vs o2switch' },
      { href: '/comparatifs/hostinger-vs-siteground', label: 'Hostinger vs SiteGround' },
      { href: '/calculateur-hebergement', label: 'Calculateur coût hébergement' },
      { href: '/guides/meilleur-hebergement-wordpress', label: 'Hébergement WordPress' },
      { href: '/alternatives/alternative-hostinger', label: 'Alternatives Hostinger' },
      { href: '/top-10-hebergement-web', label: 'Top hébergement' },
    ],
    faq: [
      { q: 'Quel hébergement choisir pour WordPress ?', a: 'Hostinger peut convenir pour démarrer à petit prix, o2switch pour une offre française simple, tandis que Kinsta ou WP Engine visent des besoins WordPress premium.' },
      { q: 'Le prix le plus bas est-il le meilleur choix ?', a: 'Pas toujours. Il faut aussi vérifier le renouvellement, les sauvegardes, les limites de ressources, le support et la facilité de migration.' },
      { q: 'Un hébergement français est-il obligatoire ?', a: 'Non, mais il peut être rassurant pour le support, la conformité et la proximité des données selon votre projet.' },
    ],
  },
  cybersecurite: {
    title: 'Cybersécurité : outils pour protéger vos comptes et systèmes',
    metaTitle: 'Cybersécurité : antivirus, gestionnaires de mots de passe, SIEM et pentest',
    description: 'Explorez les outils cybersécurité : antivirus, VPN, gestionnaires de mots de passe, MFA, scan réseau, SIEM et solutions de protection.',
    eyebrow: 'Silo Cybersécurité',
    intro: 'La cybersécurité ne se limite pas à un antivirus. Il faut combiner protection des appareils, mots de passe, MFA, surveillance et bonnes pratiques.',
    canonical: '/cybersecurite',
    primaryCta: { href: '/top-10-cybersecurite', label: 'Voir le top cybersécurité' },
    secondaryCta: { href: '/outils/cybersecurite', label: 'Explorer les outils' },
    sections: [
      { title: 'Protection utilisateur', text: 'Antivirus, VPN, gestionnaires de mots de passe et MFA couvrent les risques les plus fréquents pour les particuliers et petites équipes.' },
      { title: 'Audit et surveillance', text: 'Les outils de scan, SIEM et monitoring réseau s’adressent plutôt aux profils techniques et aux organisations.' },
      { title: 'Choix pragmatique', text: 'Nous privilégions la lisibilité, le niveau de protection, l’impact performance et la facilité d’adoption.' },
    ],
    links: [
      { href: '/top-10-cybersecurite', label: 'Top cybersécurité' },
      { href: '/top-10-antivirus', label: 'Top antivirus' },
      { href: '/comparatifs/bitdefender-vs-norton', label: 'Bitdefender vs Norton' },
      { href: '/comparatifs/bitdefender-vs-kaspersky', label: 'Bitdefender vs Kaspersky' },
      { href: '/comparatifs/avast-vs-avg', label: 'Avast vs AVG' },
      { href: '/comparatifs/dashlane-vs-1password', label: 'Dashlane vs 1Password' },
      { href: '/guides/meilleur-antivirus-pas-cher', label: 'Antivirus pas cher' },
      { href: '/alternatives/alternative-bitdefender', label: 'Alternatives Bitdefender' },
    ],
    faq: [
      { q: 'Quels outils cybersécurité installer en priorité ?', a: 'Pour un usage courant, commencez par un gestionnaire de mots de passe, l’authentification MFA, un antivirus fiable et un VPN si vous utilisez souvent des réseaux publics.' },
      { q: 'Un antivirus suffit-il ?', a: 'Non. Il protège une partie du risque, mais ne remplace pas les mises à jour, mots de passe uniques, sauvegardes et vigilance face au phishing.' },
      { q: 'Les outils techniques sont-ils adaptés aux débutants ?', a: 'Certains outils comme Wireshark, pfSense ou des scanners de vulnérabilités nécessitent un minimum de contexte technique. Les fiches doivent aider à identifier ce niveau.' },
    ],
  },
  alternatives: {
    title: 'Alternatives logiciels : remplacer un outil sans perdre en efficacité',
    metaTitle: 'Alternatives logiciels : IA, VPN, hébergement et cybersécurité',
    description: 'Trouvez les meilleures alternatives aux outils populaires : ChatGPT, NordVPN, Hostinger, Claude, Bitdefender et autres solutions tech.',
    eyebrow: 'Silo Alternatives',
    intro: 'Une alternative n’est pas seulement un outil moins cher. Elle peut mieux répondre à un usage, une contrainte de confidentialité, une intégration ou un budget.',
    canonical: '/alternatives',
    primaryCta: { href: '/alternatives/alternative-chatgpt', label: 'Alternatives ChatGPT' },
    secondaryCta: { href: '/comparatifs', label: 'Voir les comparatifs' },
    sections: [
      { title: 'Alternatives IA', text: 'Comparer ChatGPT, Claude, Gemini, Perplexity ou Mistral aide à éviter un choix basé uniquement sur la notoriété.' },
      { title: 'Alternatives VPN', text: 'Surfshark, ExpressVPN, Proton VPN ou Mullvad ne visent pas exactement les mêmes profils que NordVPN.' },
      { title: 'Alternatives hébergement et sécurité', text: 'Les hébergeurs et suites de protection doivent être comparés selon support, prix, performance et simplicité.' },
    ],
    links: [
      { href: '/alternatives/alternative-chatgpt', label: 'Alternative ChatGPT' },
      { href: '/alternatives/alternative-nordvpn', label: 'Alternative NordVPN' },
      { href: '/alternatives/alternative-hostinger', label: 'Alternative Hostinger' },
      { href: '/alternatives/alternative-bitdefender', label: 'Alternative Bitdefender' },
    ],
    faq: [
      { q: 'Pourquoi chercher une alternative ?', a: 'Pour réduire le coût, changer d’interface, améliorer la confidentialité, obtenir une fonction spécifique ou éviter une dépendance à un seul fournisseur.' },
      { q: 'Une alternative gratuite est-elle forcément meilleure ?', a: 'Non. Une version gratuite peut être utile pour tester, mais les limites, la confidentialité et le support doivent être regardés attentivement.' },
      { q: 'Comment sont choisies les alternatives ?', a: 'Nous partons de l’intention utilisateur puis comparons prix, fonctionnalités, limites, maturité et pertinence par cas d’usage.' },
    ],
  },
  guides: {
    title: 'Guides tech : choisir avec méthode',
    metaTitle: 'Guides tech : IA, VPN, hébergement, cybersécurité et logiciels',
    description: 'Guides pratiques pour choisir un outil IA, un VPN, un hébergement web, un antivirus ou une solution cybersécurité.',
    eyebrow: 'Silo Guides',
    intro: 'Les guides Comparateur-Tech répondent aux questions de choix concrètes : quel outil pour quel profil, avec quelles limites et quels points à vérifier.',
    canonical: '/guides',
    primaryCta: { href: '/methodologie', label: 'Lire notre méthode' },
    secondaryCta: { href: '/comparatifs', label: 'Explorer les comparatifs' },
    sections: [
      { title: 'Guides IA', text: 'Comprendre les assistants, les outils pour étudiants, les outils pour développeurs et les alternatives selon votre workflow.' },
      { title: 'Guides VPN et sécurité', text: 'Comparer les besoins de confidentialité, streaming, Wi-Fi public, antivirus et protection quotidienne.' },
      { title: 'Guides hébergement', text: 'Choisir selon WordPress, support, budget, performance et marge de progression.' },
    ],
    links: [
      { href: '/guides/meilleurs-outils-ia-pour-developpeurs', label: 'IA pour développeurs' },
      { href: '/guides/meilleurs-outils-ia-pour-etudiants', label: 'IA pour étudiants' },
      { href: '/guides/meilleure-ia-gratuite', label: 'Meilleure IA gratuite' },
      { href: '/guides/meilleure-api-ia', label: 'Meilleure API IA' },
      { href: '/guides/meilleur-vpn-streaming', label: 'VPN streaming' },
      { href: '/guides/meilleur-vpn-pas-cher', label: 'VPN pas cher' },
      { href: '/guides/meilleur-vpn-gratuit', label: 'VPN gratuit' },
      { href: '/guides/meilleur-vpn-android', label: 'VPN Android' },
      { href: '/guides/meilleur-vpn-iphone', label: 'VPN iPhone' },
      { href: '/guides/meilleur-gestionnaire-mots-de-passe', label: 'Gestionnaire de mots de passe' },
      { href: '/guides/gestionnaire-mots-de-passe-gratuit', label: 'Gestionnaire de mots de passe gratuit' },
      { href: '/guides/meilleur-antivirus-gratuit', label: 'Antivirus gratuit' },
      { href: '/guides/meilleur-antivirus-pas-cher', label: 'Antivirus pas cher' },
      { href: '/guides/meilleur-antivirus-mac', label: 'Antivirus Mac' },
      { href: '/guides/meilleur-antivirus-android', label: 'Antivirus Android' },
      { href: '/guides/meilleur-hebergement-wordpress', label: 'Hébergement WordPress' },
      { href: '/guides/meilleur-hebergement-pas-cher', label: 'Hébergement pas cher' },
    ],
    faq: [
      { q: 'À quoi servent les guides ?', a: 'Ils aident à comprendre les critères importants avant de lire un comparatif ou une fiche outil.' },
      { q: 'Les guides remplacent-ils un avis complet ?', a: 'Non. Ils orientent le choix et renvoient vers les comparatifs, fiches et méthodes quand un arbitrage plus précis est nécessaire.' },
      { q: 'Les guides sont-ils mis à jour ?', a: 'Les pages majeures doivent être revues régulièrement, surtout pour les prix, limites d’offres et fonctionnalités qui évoluent vite.' },
    ],
  },
};
